Semestralka/Models/ErrorViewModel.cs
using System;

namespace Semestralka.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Semestralka/Controllers/ApiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SemestralkaDataControl.EF;
using SemestralkaDataControl.Models;
using SemestralkaDataControl.Repo;
using Newtonsoft.Json;
using AutoMapper;

namespace Semestralka.Controllers
{
    [ApiController]
    [Produces("application/json")]
    public class ApiController : ControllerBase
    {
        private readonly RoomRepo _repo;

        public ApiController(RoomRepo repo)
        {
            _repo = repo;
            var config = new MapperConfiguration(cfg => {
                cfg.CreateMap<RoomWithFreeTimes, RoomWithFreeTimes>();
            });
            
           
        }

        // GET: api/Rooms/31.03.2020
        [Route("api/Rooms/{date}")]
        [HttpGet("{date}")]
        public IEnumerable<RoomWithFreeTimes> GetRooms([FromRoute]string date)
        {
            string[] parsedString = date.Split('.');
            DateTime newDateTime = new DateTime(int.Parse(parsedString[2]), int.Parse(parsedString[1]), int.Parse(parsedString[0]));
            var something = _repo.GetAllForApi(newDateTime);
            return something;
        }

        // GET: api/Rooms/31.03.2020/0
        [Route("api/Rooms/{date}/{id}")]
        [HttpGet("{date}/{id}")]
        public RoomWithFreeTimes GetRoom([FromRoute]string date, int id)
        {
            string[] parsedString = date.Split('.');
            DateTime newDateTime = new DateTime(int.Parse(parsedString[2]), int.Parse(parsedString[1]), int.Parse(parsedString[0]));
            var something = _repo.GetRoomInfoForApi(newDateTime, id);
            return something;
        }
    }
}

Semestralka/Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SemestralkaDataControl.EF;
using SemestralkaDataControl.Models;
using SemestralkaDataControl.Repo;

namespace Semestralka.Controllers
{
    public class ReservationsController : Controller
    {
        private readonly ReservationRepo _repo;

        public ReservationsController(ReservationRepo repo)
        {
            _repo = repo;
        }




        // GET: Reservations/Create
        public IActionResult Create(string date, int? timeFrom, int? id)
        {
            if (Regex.IsMatch(date, @"^\d{4}/\d{2}/\d{2}$") && timeFrom != null && id != null)
            {
                string[] splittedDate = date.Split('/');
                DateTime newDate = new DateTime(int.Parse(splittedDate[0]), int.Parse(splittedDate[1]), int.Parse(splittedDate[2]), (int)timeFrom, 0, 0);
                ViewBag.Id = id;
                ViewBag.Date = newDate;
                return View();
            }
            else
            {
                return BadRequest();
            }
        }

        // POST: Reservations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("DateAndTime,ClientName,ClientSurname,ClientEmail,ClientPhone,Description,RoomId")] Reservation reservation)
        {
            if (ModelState.IsValid)
            {       
                if (!_repo.CheckIfExists(reservation.DateAndTime))
                {
                    _repo.Add(reservation);
                }
                else
                {
                    return RedirectToAction("Details", "Rooms", new { id = reservation.RoomId, error = 1 });
                }
                return RedirectToAction("Index", "Rooms");
            }
            

            return View(reservation);
        }

     

    }
}

Semestralka/Controllers/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SemestralkaDataControl.EF;
using SemestralkaDataControl.Models;
using SemestralkaDataControl.Repo;

namespace Semestralka.Controllers
{
    public class RoomsController : Controller
    {
        private readonly RoomRepo _repo;

        public RoomsController(RoomRepo repo)
        {
            _repo = repo;
        }

        // GET: Rooms
        public ViewResult Index(int? error)
        {
           
            return View(_repo.GetAll());
        }
        [HttpPost]
        public ActionResult GetFreeReservationTimes(string date, int id)
        {
            List<int> freeTimes = null;
            if (ModelState.IsValid)
            {
                string[] dateSplitted = date.Split('-');
                
                freeTimes = _repo.GetAllFreeTimes(new DateTime(int.Parse(dateSplitted[0]), int.Parse(dateSplitted[1]), int.Parse(dateSplitted[2])), id);
            }
            return new JsonResult(freeTimes);
        }
        // GET: Rooms/Details/5
        public IActionResult Details(int? id, int? error)
        {
            if (id == null)
            {
                return NotFound();
            }
            var room = _repo.GetOne(id);
            if (room == null)
            {
                return NotFound();
            }
            if (error != null && error == 1)
            {
                ViewBag.Error = true;
            }
            return View(room);
        }


        private bool RoomExists(int id)
        {
            return _repo.GetOne(id) == null ? false : true;
        }
    }
}

Semestralka/Views/Reservations/Create.cshtml
@model SemestralkaDataControl.Models.Reservation

@{
    ViewData["Title"] = "Create";
}


@section Links {
    <link rel="stylesheet" href="~/css/reservations/create.css" asp-append-version="true" />
}

<h1>Create</h1>

<h4>Reservation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="DateAndTime" value="@ViewBag.Date" type="hidden" />
            <div class="form-group">
                <label asp-for="ClientName" class="control-label"></label>
                <input asp-for="ClientName" class="form-control" />
                <span asp-validation-for="ClientName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClientSurname" class="control-label"></label>
                <input asp-for="ClientSurname" class="form-control" />
                <span asp-validation-for="ClientSurname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClientEmail" class="control-label"></label>
                <input asp-for="ClientEmail" class="form-control" />
                <span asp-validation-for="ClientEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClientPhone" class="control-label"></label>
                <input asp-for="ClientPhone" class="form-control" />
                <span asp-validation-for="ClientPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <input asp-for="RoomId" type="hidden" value="@ViewBag.Id" />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/rooms/detail.js"></script>
}

Semestralka/Views/Rooms/Details.cshtml
@model SemestralkaDataControl.Models.Room

@{
    ViewData["Title"] = "Details";
}

@functions
{
    public string GetTodaysDateFormatted()
    {

        return String.Format("{0:yyyy-MM-dd}", DateTime.Now);
    }
    public string GetTodaysDateFormatted(DateTime datetime)
    {

        return String.Format("{0:yyyy-MM-dd}", datetime);
    }
}

@section Links {
    <link rel="stylesheet" href="~/css/rooms/detail.css" asp-append-version="true" />
}


@if (ViewBag.Error != null && ViewBag.Error == true)
{
    <div class="error">Someone has already booked reservation at this time</div>
}

<h1>Booking for room: @Model.Name</h1>
<p class="room_description">@Model.Description</p>


<div class="content-container">
    
        <div id="left-side">
            <label>Date:</label>
            <input type="date" id="date-input" name="date" min="@GetTodaysDateFormatted()">
            <a asp-action="Index" asp-controller="Rooms" class="back-link">Back</a>
        </div>

        <div id="right-side">
            <div id="right-side-content">

            </div>
        </div>
</div>



@section Scripts{
    <script src="~/js/rooms/detail.js"></script>
    <script>
        $(document).ready(function () {

            var selected = null;
            $("#date-input").change(function () {
                selected = null;
                var date = new Date($('#date-input').val());
                day = date.getDate();
                month = date.getMonth() + 1;
                year = date.getFullYear();
                $("#next").remove();
                $("#right-side-content").empty();
                if (Number.isNaN(day) || Number.isNaN(month) || Number.isNaN(year)) {
                    ("#right-side").empty();
                } else {
                    $.ajax({
                        type: "POST",
                        url: "@Url.Action("GetFreeReservationTimes")",
                        data: { date: year + "-" + month + "-" + day, id: @Model.Id },
                        dataType: "text",
                        success: function (data) {
                            var obj = JSON.parse(data);
                            
                            

                            if (obj.length == 0) {
                                $("#right-side-content").append($("<p>").addClass("warning").text("There are no free booking times for this date"));
                            } else {
                                obj.forEach(function (entry) {
                                    var toEntry = entry + 1;
                                    $("#right-side-content").append(
                                        $("<div>").addClass("freeTime").text(entry + ":00 - " + toEntry + ":00").attr("id", entry));
                                });

                                if (obj.length > 0) {
                                    $("#right-side").append($("<button>").addClass("btn-primary").attr("id", "next").text("Next"));
                                }
                                $(".freeTime").click(function () {
                                    $(".freeTime").removeClass("selected");
                                    $(this).addClass("selected");
                                    selected = $(this).attr("id");
                                });
                                $("#next").click(function () {
                                    window.location.replace("@Url.Action("Create", "Reservations")" + "?id=" +@Model.Id+"&date=" + year + "/" + month + "/" + day + "&timeFrom=" + selected);
                                });
                            }



                        }
                    });
                }
            });


        });
    </script>
}

Semestralka/Views/Rooms/Index.cshtml
@model IEnumerable<SemestralkaDataControl.Models.Room>

@{
    ViewData["Title"] = "List of Rooms";
}

@section Links {
    <link rel="stylesheet" href="~/css/rooms/index.css" asp-append-version="true" />
}


<h1>List of rooms</h1>


<div class="rooms-container">
    @foreach (var item in Model.ToList())
    {
        <div class="room">
            <p class="room_name">@item.Name</p>
            <a class="room_link" asp-controller="Rooms" asp-action="Details" asp-route-id="@item.Id">Book now!</a>
            <div class="room_description">@item.Description</div>
        </div>
    }
</div>




@section Scripts{ 
  <script src="~/js/rooms/index.js" asp-append-version="true"></script>
  <script>
      $(document).ready(function () {
          $(".room_description").each(function () {
              var truncated = this.innerHTML;
              if (truncated.length > 197) {
                  truncated = truncated.substr(0, 197) + '...';
              }
              this.innerHTML = truncated;
          });
      });
      
   
  </script>
}

Semestralka/Views/Rooms/_partialFreeTimes.cshtml
@model List<int>

@functions{
    public string GetString(int i)
    {
        return $"{i}:00";
    }
}

@foreach(var item in Model)
{
    <div class="freeTime">@GetString(item)</div>
}

Semestralka/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Semestralka</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Links", required: true);
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Rooms" asp-action="Index">Semestralka</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rooms" asp-action="Index">Rooms</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Semestralka
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>